version: '3'
services:
  postgresserver:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=restaurant_db
    expose:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynet

  rabbitmq:
    # login guest:guest
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "25672:25672"
      - "15671:15671"
      - "15672:15672"
    networks:
      - mynet

  web-api:
    build: .
    environment:
      RestaurantDbConnectionString: "Host=postgresserver;Port=5432;Database=restaurant_db;Username=postgres;Password=123456;Pooling=false;"
      RabbitmqHostName: "rabbitmq"
    ports:
      - "8090:80"
    networks:
      - mynet
    depends_on:
      - "postgresserver"
      - "rabbitmq"

networks:
  mynet:
    driver: bridge

volumes:
  pgdata:
